name: "close-milestone"
description: "Closes the given milestone if it exists"
author: "jzheaux"
inputs:
  milestone-title:
    description: "The milestone to close"
    required: true
runs:
  using: "node20"
  main: "index.js"
