name: "close-milestone"
description: "Closes the given milestone if it exists"
author: "jzheaux"
inputs:
  milestone-title:
    description: "The milestone to close"
    required: true
  repository-token:
    description: "The repository token with permissions to close milestones"
    required: true
  repository-name:
    description: "The repository containing the milestone; uses the current repository by default"
    required: false
runs:
  using: "node20"
  main: "../dist/close-milestone/main/index.js"
