name: "schedule-milestone"
description: "An action that schedules a milestone"
author: "jzheaux"
inputs:
  milestone:
    description: "The milestone to schedule; if none given, will compute based on after_milestone; otherwise, the project's current version"
    required: false
  after_milestone:
    description: "The milestone id that this milestone should follow"
    required: false
  day_of_week:
    description: "The day of the week this project releases"
    required: true
  week_of_month:
    description: "The week of the month this project releases"
    required: true


runs:
  using: "node20"
  main: ../dist/open-milestone/index.js