name: "compute-next-snapshot"
description: "An action that determines the next snapshot version for the project"
author: "jzheaux"

inputs:
  milestone-title:
    description: "The title of the current milestone"
    required: true

outputs:
  snapshot-version:
    description: "The next snapshot version for the project"
    value: ${{ steps.compute-version.outputs.version }}

runs:
  using: "node20"
  main: '../dist/compute-next-snapshot/main/index.js'