name: "schedule-milestone"
description: "An action that schedules a milestone, updating it if it already exists"
author: "jzheaux"
inputs:
  milestone-title:
    description: "The milestone to close"
    required: true
  milestone-date:
    description: "The milestone date"
    required: true
  milestone-description:
    description: "The milestone description"
    required: false
runs:
  using: "node16"
  main: "index.js"
