name: "learn-page-update-action"
description: "Update #learn Page on Spring OSS and Commercial Websites"
author: "jzheaux"
inputs:
  github-token:
    description: "The GitHub token needed to access spring-website-content or spring-website-commercial-content"
    required: true
  api-doc-url:
    description: "The URL to the project's JavaDoc; supports {version} placeholder"
    default: "https://docs.spring.io/{project}/site/docs/{version}/api/"
    required: false
  website-repository:
    description: "The Spring Website GitHub repo from which to checkout documentation files"
    required: false
    default: ''
  is-antora:
    description: "Whether the reference documentation is Antora-based; defaults to true"
    default: "true"
    required: false
  project-name:
    description: "the project name (for example, spring-security); will use repo name if not provided"
    required: false
  ref-doc-url:
    description: "The URL to the project's reference documentation; supports {version} placeholder"
    default: "https://docs.spring.io/{project}/reference/{version}/index.html"
    required: false
  version:
    description: "The current GA version; will read gradle.properties or pom.xml if not provided"
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - uses: jzheaux/learn-page-update-action@v1
      with:
        github-token: ${{ inputs.github-token }}
        api-doc-url: ${{ inputs.api-doc-url }}
        website-repository: ${{ inputs.website-repository }}
        is-antora: ${{ inputs.is-antora }}
        project-name: ${{ inputs.project-name }}
        ref-doc-url: ${{ inputs.ref-doc-url }}
        version: ${{ inputs.version }}