name: Perform Release

on:
  workflow_dispatch:

env:
  WIDGETS_REPOSITORY: 'jzheaux/spring-widgets'
  WEBSITE_REPOSITORY: 'jzheaux/jzheaux-website-content'
  GH_TOKEN: ${{ secrets.WIDGETS_TOKEN }}

jobs:
  perform-release:
    name: Perform Release
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.WIDGETS_REPOSITORY }}
          token: ${{ secrets.WIDGETS_TOKEN }}
      - id: project-version
        name: Extract Project Version
        uses: jzheaux/spring-io-actions/compute-version@main
      - name: Verify calculated version
        run: |
          echo "The version found was ${{ steps.project-version.outputs.version }}"
          echo "Is the version a snapshot? ${{ steps.project-version.outputs.snapshot }}"
      - uses: jzheaux/spring-io-actions/update-learn-page@main
        if: ${{ steps.project-version.outputs.snapshot == 'false' }}
        with:
          website-token: ${{ secrets.WEBSITE_TOKEN }}
          website-repository: ${{ env.WEBSITE_REPOSITORY }}
          version: ${{ steps.project-version.outputs.version }}
      - name: Generate Changelog
        uses: spring-io/github-changelog-generator@v0.0.12
        if: ${{ steps.project-version.outputs.snapshot == 'false' }}
        with:
          milestone: ${{ steps.project-version.outputs.version }}
          repository: ${{ env.WIDGETS_REPOSITORY }}
          token: ${{ secrets.WIDGETS_TOKEN }}
          config-file: scripts/release/release-notes-sections.yml
      - name: GitHub Release
        uses: jzheaux/spring-io-actions/publish-release-notes@main
        with:
          tag: ${{ steps.project-version.outputs.version }}
      - name: Announce Release on GChat
        uses: jzheaux/spring-io-actions/announce-on-gchat@main
        if: ${{ steps.project-version.outputs.snapshot == 'false' }}
        with:
          project-version: ${{ steps.project-version.outputs.version }}
          project-name: 'spring-widgets'
          gchat-webhook-url: ${{ secrets.GCHAT_WEBHOOK_URL }}
      - name: Close Release Milestone
        uses: jzheaux/spring-io-actions/close-milestone@main
        if: ${{ steps.project-version.outputs.snapshot == 'false' }}
        with:
          milestone-title: ${{ steps.project-version.outputs.version }}
          repository-name: ${{ env.WIDGETS_REPOSITORY }}
          repository-token: ${{ secrets.WIDGETS_TOKEN }}
      - id: next-release-milestone
        uses: jzheaux/spring-io-actions/compute-next-version@main
        if: ${{ steps.project-version.outputs.snapshot == 'false' }}
        with:
          current-version: ${{ steps.project-version.outputs.version }}
          milestone-token: ${{ secrets.WIDGETS_TOKEN }}
          website-repository: ${{ env.WEBSITE_REPOSITORY }}
          website-token: ${{ secrets.WEBSITE_TOKEN }}
          project-slug: 'spring-widgets'
      - name: Ensure Next Release Scheduled
        uses: jzheaux/spring-io-actions/schedule-milestone@main
        if: ${{ steps.next-release-milestone.outputs.release-type  == 'oss' }}
        with:
          milestone-title: ${{ steps.next-release-milestone.outputs.release-title }}
          milestone-date: ${{ steps.next-release-milestone.outputs.release-date }}
          repository-token: ${{ secrets.WIDGETS_TOKEN }}
          website-token: ${{ secrets.WEBSITE_TOKEN }}
      - id: next-next-release-milestone
        uses: jzheaux/spring-io-actions/compute-next-version@main
        if: ${{ steps.next-release-milestone.outputs.release-type  == 'oss' }}
        with:
          current-version: ${{ steps.next-release-milestone.outputs.release-title }}
          milestone-token: ${{ secrets.WIDGETS_TOKEN }}
          website-repository: ${{ env.WEBSITE_REPOSITORY }}
          website-token: ${{ secrets.WEBSITE_TOKEN }}
          project-slug: 'spring-widgets'
      - name: Ensure Next Next Release Scheduled
        uses: jzheaux/spring-io-actions/schedule-milestone@main
        if: ${{ steps.next-next-release-milestone.outputs.release-type  == 'oss' }}
        with:
          milestone-title: ${{ steps.next-next-release-milestone.outputs.release-title }}
          milestone-date: ${{ steps.next-next-release-milestone.outputs.release-date }}
          repository-token: ${{ secrets.WIDGETS_TOKEN }}
          website-token: ${{ secrets.WEBSITE_TOKEN }}
      - name: Update Version
        uses: jzheaux/spring-io-actions/push-next-development-version@main
        if: ${{ steps.project-version.outputs.snapshot == 'false' }}
        with:
          version: ${{ steps.project-version.outputs.version }}